#!/bin/sh

# Copies the latest Summix to the test installation at Mars to avoid SourceForge download

echo -n "MD5 sum: "
md5sum Summix/target/*.zip

for SITE in doms mediehub aviser; do
    scp Summix/target/*.zip summatst@mars:/home/summatst/summarise/sites/${SITE}/summix-storage
done
#scp Summix/target/*.zip summatst@mars:/home/summatst/summarise/sites/hubsolr/summix-storage
#scp Summix/target/*.zip summatst@mars:/home/summatst/summarise/sites/summonsolr/summix-storage
#scp Summix/target/*.zip summatst@mars:/home/summatst/summarise/sites/sbsolr/summix-storage
