/* $Id$
 * $Revision$
 * $Date$
 * $Author$
 *
 * The Summa project.
 * Copyright (C) 2005-2007  The State and University Library
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package dk.statsbiblioteket.summa.common.util;

import java.io.StringWriter;
import java.util.HashMap;
import java.util.Map;

import dk.statsbiblioteket.util.qa.QAInfo;

/**
 * An extension to HashMap<String, String> that disallows null-keys and values
 * and provides methods for converting the full map to and from Strings.
 */
@QAInfo(level = QAInfo.Level.NORMAL,
        state = QAInfo.State.IN_DEVELOPMENT,
        author = "te")
public class StringMap extends HashMap<String, String> {
    public StringMap(int initialCapacity, float loadFactor) {
        super(initialCapacity, loadFactor);
    }
    public StringMap(int initialCapacity) {
        super(initialCapacity);
    }
    public StringMap() {
        super();
    }

    /**
     * Override of the constructor for HashMap that ensures that no null key
     * or values are added.
     * @param map the map to base the new map on.
     */
    public StringMap(Map<? extends String, ? extends String> map) {
        super(map.size());
        putAll(map);
    }

    /**
     * Override of HashMap.put that fails in case of null key or value.
     * @param key   the key for the value to store.
     * @param value the value to store.
     * @return the old value if any.
     */
    public String put(String key, String value) {
        if (key == null) {
            throw new IllegalArgumentException("Key must not be "
                                               + "null");
        }
        if (value == null) {
            throw new IllegalArgumentException("Value must not be "
                                               + "null");
        }
        return super.put(key, value);
    }

    /**
     * Override of HashMap.putAll that fails in case of null keys or values.
     * @param map the content of the map is added to this.
     */
    public void putAll(Map<? extends String,? extends String> map) {
        for (Map.Entry<? extends String, ? extends String> entry:
                map.entrySet()) {
            put(entry.getKey(), entry.getValue());
        }
    }

    /**
     * Converts the content of the map to a single String, suitable for storage
     * in a String-only system.
     * </p><p>
     * Each entry is stored as key=value where "=" inside key or value is
     * escaped with "/e", "/" is escaped with "/s" and newline is escaped with
     * "/n". Newline is used as delimiter for entries.
     * @return a formal String-representation of the content.
     * @see {@link #fromFormalString} for the reverse function.
     */
    public String toFormalString() {
        StringWriter sw = new StringWriter(size() * 50);
        boolean first = true;
        for (Map.Entry<String, String> entry: entrySet()) {
            if (!first) {
                sw.append("\n");
            }
            sw.append(escape(entry.getKey())).append("=");
            sw.append(escape(entry.getValue()));
            first = false;
        }
        return sw.toString();
    }

    protected static String escape(String raw) {
        return raw.replace("/", "/s").replace("=", "/e").replace("\n", "/n");
    }
    protected static String unescape(String safe) {
        return safe.replace("/n", "\n").replace("/e", "=").replace("/s", "/");
    }

    /**
     * Converts the given formal String to a StringMap.
     * @param formal a formal StringMap String representation, as generated by
     *               {@link #toFormalString}.
     * @return       a StringMap generated from the formal String, or null if
     *               formal is null or empty.
     */
    public static StringMap fromFormalString(String formal) {
        if (formal == null || "".equals(formal)) {
            return null;
        }
        String[] lines = formal.split("\n");
        StringMap map = new StringMap(lines.length * 2);
        for (String line: lines) {
            // We don't use split here, as we want to support empty key/values
            int divPos = line.indexOf('=');
            if (divPos == -1) {
                throw new IllegalArgumentException("The line '" + line
                                                   + "' did not contain an =");
            }
            map.put(unescape(line.substring(0, divPos)),
                    unescape(line.substring(divPos+1, line.length())));
        }
        return map;
    }
}
