#!/bin/bash
# Updates the Maven versions in modules based on the super pom.xml

mvn -N versions:update-child-modules
VERSION=`cat pom.xml | grep -A 1 "<artifactId>summa" | tr '\n' ' ' | sed 's/.*<version>\([^>]\+\)<\/version>.*/\1/'`
echo "*** Proposed actions (not performed automatically):"
echo "svn commit -m \"Bumped to $VERSION\""

if [ "." != ".`echo $VERSION | grep SNAPSHOT`" ]; then
    exit
fi

# Real version, so we want to create a release and tag it
echo "./upload"
if [ ! -s upload.id ]; then
    echo "*** Please create the file 'upload.id' containing your SourceForge ID"
    ID="YOURSOURCEFORGEID"
else
    ID=`cat upload.id`
fi
echo "svn copy svn+ssh://${ID}@svn.code.sf.net/p/summa/code/trunk svn+ssh://${ID}@svn.code.sf.net/p/summa/code/tags/${VERSION} -m \"Release ${VERSION}\""

