#!/bin/sh

# Copies the latest Summix to the test installation at Mars to avoid SourceForge download

echo -n "MD5 sum: "
md5sum Summix/target/*.zip

scp Summix/target/*.zip summatst@mars:/home/summatst/summarise/sites/hubsolr/summix-storage
scp Summix/target/*.zip summatst@mars:/home/summatst/summarise/sites/summonsolr/summix-storage
scp Summix/target/*.zip summatst@mars:/home/summatst/summarise/sites/sbsolr/summix-storage
